/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
	"wizconnect adapter settings": {
		"en": "Adapter settings for wizconnect",
		"de": "Adaptereinstellungen für wizconnect"
	},
	"active":      {
		"en": "Active",
		"de": "Aktiviert"
	 },
	 "addresses":   {
		"en": "addresses to monitoring",
		"de": "Adresse für Monitoring"
	 },
	 "interval":    {
		"en": "Polling interval[sec]",
		"de": "Abfrage Intervall[sec]"
	 },
	 "ipaddress":   {
		"en": "IP Address",
		"de": "IP Adresse"
	 },
	 "name":        {
		"en": "Name",
		"de": "Name"
	 },
	 "settings":    {
		"en": "Adapter settings",
		"de": "Adapter-Einstellungen"
	 },
	 "bind_ip": {
		 "en": "Bind IP-Adress",
		 "de": "Lauschende IP-Adresse"
	  },
	"register_devices": {
		"en": "register devices for auto update",
		"de": "Geräte registrieren zum automatischen Update"
	},
	"polling_intervall": {
		"en": "polling intervall (s)",
		"de": "Aktualisierungsrate (s)"
	},
	"listed_online": {
		"en": "treat as online (s)",
		"de": "Als online betrachten (s)"
	},
};